apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  namespace: argocd  # Added namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: krishna33gaikwad/node-mysql-curd-app:3924c94b1f4c22b2955b5bd3be76d9a365cbac13
          ports:
            - containerPort: 3000
          env:
            - name: MYSQL_HOST
              value: "mysql-service"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: MYSQL_DB
              value: "testdb"
---
apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  namespace: argocd  # Namespace added
spec:
  type: ClusterIP  # Changed to ClusterIP
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

